### PR TITLE
Blink - Video Converter App Submission

### PR DESCRIPTION
**Pull request by osaleem303**
### .NET MAUI Beautiful UI Challenge (August 2022)

If you're submitting this during August 2022, you can enter in the [.NET MAUI Beautiful UI Challenge](https://aka.ms/maui/uichallenge)! After submitting your pull request, grab the URL and fill out the quick form at https://www.surveymonkey.com/r/maui-ui-challenge to let us know where to send your stickers!

### CODE REVIEW

**Comment by jsuarezruiz** [comment]
image

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]
Cannot access to the https://github.com/osaleem303/Blink-Design repository, maybe is not public?

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]
Could you review the conflicts?. Thanks!

**Comment by osaleem303** [comment]
> Could you review the conflicts?. Thanks!

Sure, I'll resolve these conflicts

**Comment by osaleem303** [comment]
> Cannot access to the https://github.com/osaleem303/Blink-Design repository, maybe is not public?

Is it mandatory to make this repo public? 
Either way I do have plan to make it public in couple of days as I do have some clutter to clear up :)

**Pull request closed without merging**
